import time
import os

def clippy():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@. =*")
    print("             -@-@:   =@ -@:")
    print("             :@-@:   -@ *@")
    print("              @=%+   .@.*%")
    print("              %#=@.  :@.=@")
    print("              +@ =%**%= -@:")
    print("               @+       -@:")
    print("               =@:      +@")
    print("                =@+.  :*%:")
    print("                 .=***+-")

def clippy2():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.   =*")
    print("             -@-@:   =@   -@:")
    print("             :@-@:   -@   *@")
    print("              @=%+   .@.  *%")
    print("              %#=@.  :@.  =@")
    print("              +@ =%**%=   -@:")
    print("               @+         -@:")
    print("               =@:        +@")
    print("                =@+.    :*%:")
    print("                 .=***+-")
    
def clippy3():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.  ")
    print("             -@-@:   =@    =*")
    print("             :@-@:   -@   -@:")
    print("              @=%+   .@.  *@")
    print("              %#=@.  :@.  *%")
    print("              +@ =%**%=   =@")
    print("               @+         -@:")
    print("               =@:        -@:")
    print("                =@+.      +@")
    print("                 .=***+-:*%:")

def clippy4():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.  ")
    print("             -@-@:   =@    ")
    print("             :@-@:   -@       =*")
    print("              @=%+   .@.      -@:")
    print("              %#=@.  :@.      *@")
    print("              +@ =%**%=       =@")
    print("               @+             =@")
    print("               =@:            -@:")
    print("                =@+.        -@:")
    print("                 .=***+-:*%:+@")

def clippy5():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.  ")
    print("             -@-@:   =@    ")
    print("             :@-@:   -@         =*")
    print("              @=%+   .@.        -@:")
    print("              %#=@.  :@.        *@")
    print("              +@ =%**%=         =@")
    print("               @+              =@")
    print("               =@:            -@:")
    print("                =@+.        -@:")
    print("                 .=***+-:*%:+@")

def clippy6():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.  ")
    print("             -@-@:   =@    ")
    print("             :@-@:   -@           =*")
    print("              @=%+   .@.          -@:")
    print("              %#=@.  :@.          *@")
    print("              +@ =%**%=           =@")
    print("               @+                =@")
    print("               =@:            -@:")
    print("                =@+.        -@:")
    print("                 .=***+-:*%:+@")

def clippy7():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.  ")
    print("             -@-@:   =@    ")
    print("             :@-@:   -@             =*")
    print("              @=%+   .@.            -@:")
    print("              %#=@.  :@.            *@")
    print("              +@ =%**%=           =@")
    print("               @+                =@")
    print("               =@:            -@:")
    print("                =@+.        -@:")
    print("                 .=***+-:*%:+@")

def clippy8():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.  ")
    print("             -@-@:   =@    ")
    print("             :@-@:   -@               =*")
    print("              @=%+   .@.              -@:")
    print("              %#=@.  :@.            *@")
    print("              +@ =%**%=           =@")
    print("               @+                =@")
    print("               =@:            -@:")
    print("                =@+.        -@:")
    print("                 .=***+-:*%:+@")

def clippy9():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.  ")
    print("             -@-@:   =@    ")
    print("             :@-@:   -@                 =*")
    print("              @=%+   .@.              -@:")
    print("              %#=@.  :@.            *@")
    print("              +@ =%**%=           =@")
    print("               @+                =@")
    print("               =@:            -@:")
    print("                =@+.        -@:")
    print("                 .=***+-:*%:+@")

def clippy10():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.                 ")
    print("             -@-@:   =@                  =*")
    print("             :@-@:   -@               -@:")
    print("              @=%+   .@.            *@")
    print("              %#=@.  :@.           =@")
    print("              +@ =%**%=         =@")
    print("               @+              -@:")
    print("               =@:          -@:")
    print("                =@+.        +@")
    print("                 .=***+-:*%:")

def clippy11():
    print("                :*####=")
    print("               *%:    +%")
    print("            _+*@#-    .@-")
    print("              *#      =@#+:")
    print("             =*#      =+    ")
    print("         .-=*+:==#    .*.   ")
    print("            +*%    :--#@%-#=")
    print("             -@.      _++")
    print("             -@:%:   =@.                  =*")
    print("             -@-@:   =@                 -@:")
    print("             :@-@:   -@               *@")
    print("              @=%+   .@.            =@")
    print("              %#=@.  :@.         =@")
    print("              +@ =%**%=       -@:")
    print("               @+           -@:")
    print("               =@:        +@")
    print("                =@+.  :*%:")
    print("                 .=***+-")

def clippy12():
    print("                :*####=")
    print("               *%:    +%")
    print("            _+*@#-    .@-")
    print("              *#      =@#+:")
    print("             =*#      =+    ")
    print("         .-=*+:==#    .*.   ")
    print("            +*%    :--#@%-#=")
    print("             -@.      _++")
    print("             -@:%:   =@.                 =*")
    print("             -@-@:   =@               -@:")
    print("             :@-@:   -@             *@")
    print("              @=%+   .@.        =@")
    print("              %#=@.  :@.     =@")
    print("              +@ =%**%=   -@:")
    print("               @+       -@:")
    print("               =@:      +@")
    print("                =@+.  :*%:")
    print("                 .=***+-")

def clippy13():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.               =*")
    print("             -@-@:   =@             -@:")
    print("             :@-@:   -@           *@")
    print("              @=%+   .@.      =@")
    print("              %#=@.  :@.   =@")
    print("              +@ =%**%= -@:")
    print("               @+       -@:")
    print("               =@:      +@")
    print("                =@+.  :*%:")
    print("                 .=***+-")

def clippy14():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.             =*")
    print("             -@-@:   =@           -@:")
    print("             :@-@:   -@        *@")
    print("              @=%+   .@.   =@")
    print("              %#=@.  :@.=@")
    print("              +@ =%**%= -@:")
    print("               @+       -@:")
    print("               =@:      +@")
    print("                =@+.  :*%:")
    print("                 .=***+-")

def clippy15():
    print("                :*####=")
    print("               *%:    +%")
    print("            -+*@#-    .@-")
    print("           :  *#      =@#+:")
    print("            =*+:=-    =+.:-=")
    print("         .-:%@@*=#   .**+.*.")
    print("          .=+*%*=  :--#@%-#=")
    print("             -@.    .*%*++:")
    print("             -@:%:   =@.          =*")
    print("             -@-@:   =@        -@:")
    print("             :@-@:   -@     *@")
    print("              @=%+   .@. =@")
    print("              %#=@.  :@.=@")
    print("              +@ =%**%= -@:")
    print("               @+       -@:")
    print("               =@:      +@")
    print("                =@+.  :*%:")
    print("                 .=***+-")

def clippy16():
    print("                :*####=")
    print("               *%:    +%")
    print("            _+*@#-    .@-")
    print("              *#      =@#+:")
    print("             =*#      =+    ")
    print("         .-=*+:==#    .*.   ")
    print("            +*%    :--#@%-#=")
    print("             -@.      _++")
    print("             -@:%:   =@.    =*")
    print("             -@-@:   =@  -@:")
    print("             :@-@:   -@ *@")
    print("              @=%+   .@.=@")
    print("              %#=@.  :@.=@")
    print("              +@ =%**%= -@:")
    print("               @+       -@:")
    print("               =@:      +@")
    print("                =@+.  :*%:")
    print("                 .=***+-")

def clippy17():
    print("                :*####=")
    print("               *%:    +%")
    print("            _+*@#-    .@-")
    print("              *#      =@#+:")
    print("             =*#      =+    ")
    print("         .-=*+:==#    .*.   ")
    print("            +*%    :--#@%-#=")
    print("             -@.      _++")
    print("             -@:%:   =@.   =*")
    print("             -@-@:   =@ -@:")
    print("             :@-@:   -@ *@")
    print("              @=%+   .@.=@")
    print("              %#=@.  :@.=@")
    print("              +@ =%**%= -@:")
    print("               @+       -@:")
    print("               =@:      +@")
    print("                =@+.  :*%:")
    print("                 .=***+-")

def time_sleep():
    time.sleep(0.1)

def clear():
    os.system("cls" if os.name == "nt" else "clear")

def animacao():
    while True:
        # Limpa o terminal antes de imprimir a próxima caveira
        clippy()
        time_sleep()
        clear()
        clippy2()
        time_sleep()
        clear()
        clippy3()
        time_sleep()
        clear()
        clippy4()
        time_sleep()
        clear()
        clippy5()
        time_sleep()
        clear()
        clippy6()
        time_sleep()
        clear()
        clippy7()
        time_sleep()
        clear()
        clippy8()
        time_sleep()
        clear()
        clippy9()
        time_sleep()
        clear()
        clippy10()
        time_sleep()
        clear()
        clippy11()
        time_sleep()
        clear()
        clippy12()
        time_sleep()
        clear()
        clippy13()
        time_sleep()
        clear()
        clippy14()
        time_sleep()
        clear()
        clippy15()
        time_sleep()
        clear()
        clippy16()
        time_sleep()
        clear()
        
if __name__ == "__main__":
    try:
        animacao()
    except KeyboardInterrupt:
        print("\nAnimação encerrada.")